source 'https://rubygems.org/'

gem 'motion-testflight'
gem 'bubble-wrap'
gem 'motion-addressbook'
#gem 'ProMotion', git: 'git://github.com/clearsightstudio/ProMotion.git'
gem 'ProMotion'
#gem 'sugarcube', require: 'sugarcube-classic'
gem 'sugarcube'
gem 'formotion'
gem 'afmotion'
gem 'motion-cocoapods'
gem 'cocoapods'
gem 'motion-layout', git: 'git://github.com/wejn/motion-layout.git', branch: 'add-options'
gem 'helu'
